9

diff --git a/.github/workflows/1.env_var_workflow_level.yml b/.github/workflows/1.env_var_workflow_level.yml
--- a/.github/workflows/1.env_var_workflow_level.yml
+++ b/.github/workflows/1.env_var_workflow_level.yml
@@ -16,31 +16,41 @@ env:
 
 jobs:
 
-  job1:
+  build:
     runs-on: ubuntu-latest
-
     steps:
-      - name: using shell-style variable expansion
-        run: |
-          echo "workflow env var1: $var1"
+      - run: exit 1  # This job fails
 
-      - name: using GH actions expression syntax
-        run: |
-          echo workflow env var2: ${{env.var2}}
+  # job1:
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - name: using shell-style variable expansion
+  #       run: |
+  #         echo "workflow env var1: $var1"
+
+  #     - name: using GH actions expression syntax
+  #       run: |
+  #         echo workflow env var2: ${{env.var2}}
      
-      - name: step3, using if statement
-        if: ${{ always() && env.var1 == 'Hello From workflow Level 1' }}
-        run: |
-          echo The result of 2 * 3 * 6 is: $((2 * 3 * 6))
-          echo The result of 2 * 3 * 6 / 12 is: $(((2 * 3 * 6) / 12))
-          echo The result of 2 * 3 * 6 / 12 + 7 is: $((((2 * 3 * 6) / 12) + 7))
+  #     - name: step3, using if statement
+  #       if: ${{ always() && env.var1 == 'Hello From workflow Level 1' }}
+  #       run: |
+  #         echo The result of 2 * 3 * 6 is: $((2 * 3 * 6))
+  #         echo The result of 2 * 3 * 6 / 12 is: $(((2 * 3 * 6) / 12))
+  #         echo The result of 2 * 3 * 6 / 12 + 7 is: $((((2 * 3 * 6) / 12) + 7))
 
-  job2:
-    runs-on: ubuntu-latest
+  # job2:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: step1, 
-        run: |
-          echo workflow env var1: $var1
-          echo workflow env var2: ${{ env.var2 }}
+  #   steps:
+  #     - name: step1, 
+  #       run: |
+  #         echo workflow env var1: $var1
+  #         echo workflow env var2: ${{ env.var2 }}
   
+  notify:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "Send notification even if build fails"
