Update chaining-jobs.yaml

diff --git a/.github/workflows/chaining-jobs.yaml b/.github/workflows/chaining-jobs.yaml
--- a/.github/workflows/chaining-jobs.yaml
+++ b/.github/workflows/chaining-jobs.yaml
@@ -21,7 +21,7 @@ job-2:
   steps:
     - name: Output for Job 2
       run: echo "Hello from Job 2"
-    - name: Make Job 2 Fail
-      run: exit 1
+    #- name: Make Job 2 Fail
+      #run: exit 1
     
       
