Update chaining-jobs.yaml

diff --git a/.github/workflows/chaining-jobs.yaml b/.github/workflows/chaining-jobs.yaml
--- a/.github/workflows/chaining-jobs.yaml
+++ b/.github/workflows/chaining-jobs.yaml
@@ -7,21 +7,21 @@ on:
         required: true
         type: boolean
 jobs:
-  job-1:
+  Job-1:
     name: Job 1
     runs-on: ubuntu-latest
     steps:
       - name: Output for job 1
         run: echo "Hello from Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"
-job-2:
-  name: Job 2
-  runs-on: ubuntu-latest
-  needs:
-      - job-1
-  steps:
-    - name: Output for Job 2
-      run: echo "Hello from Job 2"
-    #- name: Make Job 2 Fail
-      #run: exit 1
+  Job-2:
+    name: Job 2
+    runs-on: ubuntu-latest
+    needs:
+        - Job-1
+    steps:
+      - name: Output for Job 2
+        run: echo "Hello from Job 2"
+      #- name: Make Job 2 Fail
+        #run: exit 1
     
       
